# Automatically Generated Makefile by EDE.
# For use with: make
#
# DO NOT MODIFY THIS FILE OR YOUR CHANGES MAY BE LOST.
# EDE is the Emacs Development Environment.
# http://cedet.sourceforge.net/ede.shtml
#
CPPFLAGS=-Wall -Wextra -ansi -pedantic -O2

top="$(CURDIR)"/
ede_FILES=Project.ede Makefile

test_SOURCES=test.cpp Dimensions.cpp JNoun.cpp utils.cpp JVerbs.cpp JArithmeticVerbs.cpp VerbHelpers.cpp JBasicAdverbs.cpp JGrammar.cpp JBasicConjunctions.cpp JMachine.cpp JParser.cpp ParsedNumbers.cpp JEvaluator.cpp JToken.cpp Trains.cpp Locale.cpp JExecutor.cpp ShapeVerbs.cpp Gerund.cpp JTypes.cpp Aggregates.cpp
test_OBJ= test.o Dimensions.o JNoun.o utils.o JVerbs.o JArithmeticVerbs.o VerbHelpers.o JBasicAdverbs.o JGrammar.o JBasicConjunctions.o JMachine.o JParser.o ParsedNumbers.o JEvaluator.o JToken.o Trains.o Locale.o JExecutor.o ShapeVerbs.o Gerund.o JTypes.o Aggregates.o
CXX= g++
CXX_COMPILE=$(CXX) $(DEFS) $(INCLUDES) $(CPPFLAGS) $(CFLAGS)
CXX_DEPENDENCIES=-Wp,-MD,.deps/$(*F).P
CXX_LINK=$(CXX) $(CFLAGS) $(LDFLAGS) -L.
LDDEPS= -lboost_unit_test_framework -lboost_regex
VERSION=1.0
DISTDIR=$(top)J-$(VERSION)
top_builddir = 

DEP_FILES=.deps/test.P .deps/Dimensions.P .deps/JNoun.P .deps/utils.P .deps/JVerbs.P .deps/JArithmeticVerbs.P .deps/VerbHelpers.P .deps/JBasicAdverbs.P .deps/JGrammar.P .deps/JBasicConjunctions.P .deps/JMachine.P .deps/JParser.P .deps/ParsedNumbers.P .deps/JEvaluator.P .deps/JToken.P .deps/Trains.P .deps/Locale.P .deps/JExecutor.P .deps/ShapeVerbs.P .deps/Gerund.P .deps/JTypes.P .deps/Aggregates.P .deps/JGrammar.P .deps/J.P .deps/Dimensions.P .deps/JNoun.P .deps/utils.P .deps/JVerbs.P .deps/JExceptions.P .deps/JArithmeticVerbs.P .deps/VerbHelpers.P .deps/JAdverbs.P .deps/JBasicAdverbs.P .deps/JConjunctions.P .deps/JBasicConjunctions.P .deps/JMachine.P .deps/JParser.P .deps/ParserCombinators.P .deps/ParsedNumbers.P .deps/JEvaluator.P .deps/JToken.P .deps/Trains.P .deps/Locale.P .deps/JExecutor.P .deps/ShapeVerbs.P .deps/Gerund.P .deps/JTypes.P .deps/Aggregates.P

all: test

DEPS_MAGIC := $(shell mkdir .deps > /dev/null 2>&1 || :)
-include $(DEP_FILES)

%.o: %.cpp
	@echo '$(CXX_COMPILE) -c $<'; \
	$(CXX_COMPILE) $(CXX_DEPENDENCIES) -o $@ -c $<

test: $(test_OBJ)
	$(CXX_LINK) -o $@ $^ $(LDDEPS)

tags: 


clean:
	rm -f *.mod *.o *.obj .deps/*.P .lo

.PHONY: dist

dist:
	rm -rf $(DISTDIR)
	mkdir $(DISTDIR)
	cp $(test_SOURCES) $(ede_FILES) $(DISTDIR)
	tar -cvzf $(DISTDIR).tar.gz $(DISTDIR)
	rm -rf $(DISTDIR)

Makefile: Project.ede
	@echo Makefile is out of date!  It needs to be regenerated by EDE.
	@echo If you have not modified Project.ede, you can use 'touch' to update the Makefile time stamp.
	@false



# End of Makefile
